export const CHANGE_SORT_BY = "CHANGE_SORT_BY";
export const CHANGE_RARITIES = "CHANGE_RARITIES";
export const CHANGE_PACK_SLUGS = "CHANGE_PACK_SLUGS";
export const LIST_FETCHED = "LIST_FETCHED";
export const CHANGE_PAGE_NUMBER = "CHANGE_PAGE_NUMBER";
